### PR TITLE
completed changes to finish successfully merging invoice canister cleanup

### PR DESCRIPTION
**Pull request by atengberg**
Before the pull request for the [Invoice Canister BNT2](https://github.com/dfinity/grant-rfps/issues/2) can be created and submitted, there is an existing pull request [invoice canister cleanup #356](https://github.com/dfinity/examples/pull/356) that required some refactoring to bring the project's code up to date with `dfx` before it could merged without conflicts:

- upgrading the project's initialization script to use the `dfx nns` command to install/reset an ICP ledger canister locally
- updating the creation of actors' agents to conform to the `networks.json` configuration 
- updating account identifiers used in the E2E testing that changed with newer versions of `@dfinity/identity`
- adding a check invoices created have a minimum amount due to prevent trapping when funds are moved between subaccounts
- updating the `motoko-client-seller` example to reflect the "newer" path directory layout of `dfx` created projects
- some additional cleanup and necessary revision of readmes 

With this all the tests also pass successfully. With the completion of this pull request, #356 should also be able to be closed.

_Note this pull request is coming from the fork I made of the examples repo, starting off from the last commit of the aforementioned pull request_

### CODE REVIEW

**Comment by AshtonEngberg** [comment]
I had made the mistake of deciding immediately before the submitting this PR I should pull master of dfinity's example repo into my local master branch and then merge it into this branch: doing so included a lot of changes from other people's work I had no business altering so I reverted this branch to [ec2924b](https://github.com/dfinity/examples/pull/429/commits/ec2924b485edceb7bf83fea4534a7516748bc445) which is why there was a force push at [66753be](https://github.com/dfinity/examples/pull/429/commits/66753becea6fcacbdfd85f647a7222de8339ee01).

It says there are unresolved conflicts from this requiring write access, although I fixed these conflicts and [pushed](https://github.com/AshtonEngberg/examples/tree/ashton/invoice-finish-cleanup-merge/motoko/invoice-canister) them already. For who ever has to deal with this, here's the direct link to the correct version of each file already pushed that's listed in that notice:

- [motoko/invoice-canister/examples/motoko-seller-client/README.md](https://github.com/AshtonEngberg/examples/blob/ashton/invoice-finish-cleanup-merge/motoko/invoice-canister/examples/motoko-seller-client/README.md)
   _updated to reflect frontend readme was combined into this file and the correct port now used_
- motoko/invoice-canister/examples/motoko-seller-client/frontend/README.md 
   _removed entirely (refactored into the above file)_
- [motoko/invoice-canister/examples/motoko-seller-client/webpack.config.js](https://github.com/AshtonEngberg/examples/blob/ashton/invoice-finish-cleanup-merge/motoko/invoice-canister/examples/motoko-seller-client/webpack.config.js)
  _added polyfill crypto-browserify; updated correct port now used; edited to match updated directory layout now used_
- [motoko/invoice-canister/test/e2e/src/maxCapacity.js](https://github.com/AshtonEngberg/examples/blob/ashton/invoice-finish-cleanup-merge/motoko/invoice-canister/test/e2e/src/maxCapacity.js) 
  _should be unchanged_
- [motoko/invoice-canister/test/e2e/src/utils/identity.js](https://github.com/AshtonEngberg/examples/blob/ashton/invoice-finish-cleanup-merge/motoko/invoice-canister/test/e2e/src/utils/identity.js)
   _updated correct port now used_

I'll confirm the correct process before submitting the PR for bnt2, which is close to completion, to prevent additional conflicts like this (on that note, my local file system gitignore is also correctly setup for dfx projects now).

**Comment by domwoe** [comment]
Hey @AshtonEngberg,

you should be able to fix the conflicts by merging the current remote master or rebasing the current remote master. This should allow to you to fix the conflicts locally.

**Comment by AshtonEngberg** [comment]
I believe I already did--the links in my reply were to the fixed versions of those specific files that I (thought) I pushed. 

For instance, if one navigates to "Files Changed" tab and scrolls to:
[Files Changed(81) >> motoko/invoice-canister/test/e2e/src/utils/identity.js ](https://github.com/dfinity/examples/pull/429/files#diff-23b69a61f5d43bcd4ddf197de1b6aac98a099a6a132ca21b63aa28049a6c965b) 
this change was to update the ip and port the agent uses in two places (the correct ip/port is now 127.0.0.1:8080). 

It is correct [here](https://github.com/AshtonEngberg/examples/blob/ashton/invoice-finish-cleanup-merge/motoko/invoice-canister/test/e2e/src/utils/identity.js#L35) and [here](https://github.com/AshtonEngberg/examples/blob/ashton/invoice-finish-cleanup-merge/motoko/invoice-canister/test/e2e/src/utils/identity.js#L47) in the current version of the latest push as far as I can tell. 

This is similarly true for all 5 conflicts--is there something else I am missing?

**Comment by atengberg** [comment]
Since I'm pushing the completed BNT-2 PR, this can be closed.

**Pull request closed without merging**
