### PR TITLE
Rename the rust dao example to match the motoko name

### PR DESCRIPTION
**Pull request by akhi3030**
This is needed to be compliant with the requirements that the sample dapps in the different languages have the same name.

### CODE REVIEW

**Review by chenyan-dfinity — APPROVED** [review]

**Review by chenyan-dfinity — CHANGES_REQUESTED** [review]
Wait, we need to update the dfx.json as well.

**Comment by rstout** [comment]
There are many uses of `basic_dao` in the code (e.g. Makefile), do we want to update those as well?

**Comment by chenyan-dfinity** [comment]
Yep, those as well. Otherwise, it won't build.

**Comment by rstout** [comment]
Also, why change this from `basic_dao` to `dao`? We should be explicit that this is a basic/template project. I've also recorded a talk on this dapp and `basic_dao` is mentioned a lot, it would be confusing to rename it. Why not change the Motoko version, which isn't as prolific yet?

**Comment by akhi3030** [comment]
> Also, why change this from `basic_dao` to `dao`? We should be explicit that this is a basic/template project. I've also recorded a talk on this dapp and `basic_dao` is mentioned a lot, it would be confusing to rename it. Why not change the Motoko version, which isn't as prolific yet?

I picked one to change at random.  Happy to rename the motoko version to `basic_dao`.  @chenyan-dfinity : are you able to work on that please?  I'll close this PR then.

**Pull request closed without merging**
