### PR TITLE
Add ic-pos to motoko examples

### PR DESCRIPTION
**Pull request by kristoferlund**
**Overview**

This PR adds the ckBTC Point of Sale example app (Motoko) to the repository. The original repo can be found here: https://github.com/kristoferlund/ic-pos

> IC-POS is an experimental app to demonstrate a real world use case for ckBTC on the Internet Computer. It is a simple Point of Sale app that allows users to accept ckBTC payments.

For more details about IC-POS, see the README.

### CODE REVIEW

**Comment by letmejustputthishere** [comment]
hey @kristoferlund , thank you for adding this example! very happy to see community contributions 🎉 
i'll create PRs for potential changes in your repo instead of on this PR. do you have a good flow in mind to keep this example updated with future changes from the upstream repo?

**Comment by letmejustputthishere** [comment]
@kristoferlund see here
https://github.com/kristoferlund/ic-pos/pull/4

**Comment by kristoferlund** [comment]
Looks great @letmejustputthishere, thanks! Have been on vacation but am back in business now. I'll take a closer look and merge the coming days. 

I have not considered a good flow keeping the main repo and dfinity-examples in sync. Don't know to what extent that is possible. As I am not planning any more development on ic-pos for now, this time I will copypaste your changes between repos.

**Comment by letmejustputthishere** [comment]
@kristoferlund if you merge this with upstream i think we are good to go :)

are there any changes that need to be done here https://github.com/dfinity/portal/pull/1892?

**Review by letmejustputthishere — APPROVED** [review]

**Pull request merged**
