### PR TITLE
invoice canister cleanup

### PR DESCRIPTION
**Pull request by krpeacock**
**Overview**
Takes care of several cleanup tasks from #292

### CODE REVIEW

**Review by lwshang — APPROVED** [review]

**Comment by domwoe** [comment]
Would be great if we could get this merged since we now have someone working on the bounty to work on the Invoice canister.

**Comment by sesi200** [comment]
Need to fix tests first

**Comment by domwoe** [comment]
@sesi200 Do you know what the issue is here?

**Comment by sesi200** [comment]
Something in the node scripts about calling `rm` on a non-existent file is currently the error that happens, but I don't remember anymore

**Comment by AshtonEngberg** [comment]
Does anyone know if deploying a ledger canister as per https://internetcomputer.org/docs/current/developer-docs/integrations/ledger/ledger-local-setup is going to be deprecated in favor of using `nns install`/`import`? 

This is where the error is resulting from (the `nns install` adds the ledger wasm and the did corresponding to the public version of the interface yet the test script is redeploying the ledger canister using the previous method which requires the private version of the did interface which doesn't explicitly exist afaik when using `nns install`).

**Comment by sesi200** [comment]
Yes, it'll change to `nns install`, but that will still take considerable time. We want to make this the first plugins for dfx. I think it's fine to change to `nns install` for the moment, even if we'll have to change it around again later.

**Comment by AshtonEngberg** [comment]
So it's possible to use `nns install` instead of manually downloading the ledger wasm and swapping its private and public did files while installing. Simply rerunning `nns install` and `nns import` after starting dfx --clean will overwrite the ledger canister already installed this way. One thing is though if using `nns-ledger` it has to run configured in the system type subnet, so it can't be (afaik) deployed other than using `nns install` which means all 7 of the other nns canisters will also be installed each time this command is run. 

Additionally, the first ident-1.pem file (in the icjs / nns repo) corresponds to one of the two test accounts the nns-ledger is created with which can replace using the MINTER identity. Unless there's a problem with resetting the icp ledger canister state this way for the E2E tests, this should work. I've got to go through the E2E testing to make sure the identities still correctly map, but I can post this as a fix to resolve this to finish merging this PR unless anyone sees a problem?

**Comment by sesi200** [comment]
That would be great, @AshtonEngberg. Thank you for offering to help!

**Comment by AshtonEngberg** [comment]
I finished the changes to get things working for the pull request. I forked examples, and pushed the changes as a new branch off this pr branch you can view here: https://github.com/AshtonEngberg/examples/tree/ashton/invoice-finish-cleanup-merge

In the base invoice/ there's a steps-to-complete-merge.txt which outlines what was done (not necessary but for thoroughness). 

While things work, using `dfx nns install` / nns-ledger might have drawbacks that are beyond my decision making. Using the nns-ledger as provided by `dfx nns install` means 1) the networks.json configuration has to match the specs for these canisters--is there a way to setup separate local network declarations? (not all projects require subnet type to be system, or the 8080 port). 2a) Resetting the nns-ledger afaik has to be done through rerunning `dfx nns install` (upgrade, install, are not available to run on it) which means all 8 nns canisters are deployed each time the install script is run. While not a problem in itself, is perhaps not optimal? 

Additionally is that the canister id import of the nns-ledger in the invoice.mo does not resolve correctly the first time the invoice canister is built (which must happen each time the reinstall script is run). Presumably from how the nns-ledger is installed, it's canister id is not produced the 'normal' way and does not show up in .dfx/canisterids.json. However, if the invoice canister is immediately built again it will resolve and compile correctly; this is equivalent to running deploy twice in a row. At this point, calls on the nns-ledger from the invoice canister do work as they normally would. This is noted in the new install script logic. 

If these are too much of an issue and do not have another means of resolution, reverting to the previous method of installing the ICP ledger canister could be used.

**Comment by domwoe** [comment]
@AshtonEngberg  Thank you!

I think it is best to create a new PR.

**Comment by AshtonEngberg** [comment]
Separate from the pull request for the invoice bounty?

**Comment by domwoe** [comment]
> Separate from the pull request for the invoice bounty?

yep, I'd suggest we merge this first.

**Comment by domwoe** [comment]
@krpeacock can we close this PR in favor of #429 ?

**Comment by krpeacock** [comment]
@domwoe yes

**Pull request closed without merging**
