### PR TITLE
Add threshold ecdsa examples

### PR DESCRIPTION
**Pull request by ninegua**
Example code demonstrates how to use the threshold ECDSA feature. They work both in the local dfx development environment and on main net.

### CODE REVIEW

**Review by ericswanson-dfinity — COMMENTED** [review]
The only thing I see missing is a github workflow similar to the others in  https://github.com/dfinity/examples/tree/master/.github/workflows

**Comment by ninegua** [comment]
I'm getting CI failures like this:
```
Jul 25 22:54:38.835 WARN s:3kau7-pxdkc-hy5ve-vqdrj-lhg45-baoiz-dc3ne-4ccp3-o72f3-whf2r-aae/n:im4ku-moszu-2qfe7-tveps-oef7d-m7kob-l3goz-4q6yx-ziap7-baz56-dqe/ic_execution_environment/scheduler At Round 4 @ time 2022-07-25 22:54:37.955831 UTC, the resulted state after execution does not hold the in-out cycles invariant: cycles at beginning of round 0 were fewer than cycles at end of round 100000000000000, messaging: {"round":4,"canister_id":null,"message_id":null}
```

Not sure why it is happening. Maybe the CI is running too many examples and run out of cycles?

**Comment by ericswanson-dfinity** [comment]
> I'm getting CI failures like this:
> 
> ```
> Jul 25 22:54:38.835 WARN s:3kau7-pxdkc-hy5ve-vqdrj-lhg45-baoiz-dc3ne-4ccp3-o72f3-whf2r-aae/n:im4ku-moszu-2qfe7-tveps-oef7d-m7kob-l3goz-4q6yx-ziap7-baz56-dqe/ic_execution_environment/scheduler At Round 4 @ time 2022-07-25 22:54:37.955831 UTC, the resulted state after execution does not hold the in-out cycles invariant: cycles at beginning of round 0 were fewer than cycles at end of round 100000000000000, messaging: {"round":4,"canister_id":null,"message_id":null}
> ```
> 
> Not sure why it is happening. Maybe the CI is running too many examples and run out of cycles?

I asked about that type of error message when they started showing up in the replica.  It turns out they aren't a problem.  The cause of the CI failures is a little further on in the output:
```
if (!cond) throw new Error(msg)
             ^

Error: Expected signature to be an Uint8Array with length [64](https://github.com/dfinity/examples/runs/7511446102?check_suite_focus=true#step:4:65)
    at assert (/Users/runner/work/examples/examples/motoko/threshold-ecdsa/node_modules/secp256k1/lib/index.js:18:20)
    at isUint8Array (/Users/runner/work/examples/examples/motoko/threshold-ecdsa/node_modules/secp256k1/lib/index.js:31:7)
```

**Comment by ninegua** [comment]
Turns out I need the latest 0.11.1-beta2 to make it work. Also need some cross platform tweaks to the testing script.

**Review by ericswanson-dfinity — APPROVED** [review]

**Pull request merged**
